name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Login to docker
      run: docker login -u ${{ secrets.DOCKER_NAME }} -p  ${{ secrets.DOCKER_PASSWORD }}
    - name: build image
      run: |
        docker build -t ${{ secrets.DOCKER_NAME }}/simplon-app:0.1 .
        docker push ${{ secrets.DOCKER_NAME }}/simplon-app:0.1
